services:
  - name: database
    image: mariadb
    env:
      - key: MARIADB_ROOT_PASSWORD
        value: root
      - key: MARIADB_DATABASE
        value: test
    healthcheck:
      type: cmd
      cmd: ["mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - external: 3307
        internal: 3306
    volumes:
      - ./migrations/01-create-table.up.sql:/docker-entrypoint-initdb.d/migration.sql

  - name: my-service
    buildCommand: |
      cp /app/go-chat-docker /go/bin/
    env: {}
    instanceCount: 1
    plan: starter
    startCommand: /go/bin/go-chat-docker
    stopCommand: ""
    ports:
      - external: 8181
        internal: 8080
      - external: 2345
        internal: 2345

  - name: adminer
    image: adminer
    ports:
      - external: 8080
        internal: 8080

networks:
  - name: my_network
